<?php

namespace AppBundle\Repository;

/**
 * ExpertiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertiseRepository extends \Doctrine\ORM\EntityRepository
{
}
