<?php

namespace AppBundle\Repository;

/**
 * MobilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobilityRepository extends \Doctrine\ORM\EntityRepository
{
}
