<?php

namespace AppBundle\Repository;

/**
 * ProductOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
